name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
          python-version: 3.8
    - name: make hw1
      working-directory: ./hw1/src
      run: |
          make debug
          make 
    - name: test hw1
      working-directory: ./hw1
      run: |
          python3 test_syntax_error.py
    - name: make hw2
      working-directory: ./hw2/src
      run: make
    - name: test hw2
      working-directory: ./hw2
      run: |
          python3 test.py
    - name: setup bison and flex
      run: sudo apt install bison flex-old
    - name: make hw3
      working-directory: ./hw3/src
      run: make
    - name: make hw4
      working-directory: ./hw4
      run: make
    - name: make hw5
      working-directory: ./hw5/src
      run: make
    - name: make hw6
      working-directory: ./hw6/src
      run: make
    

